2024-05-15 20:37:07,448 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Configure stats pid to 71108
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Loading settings from /Users/lisa/.config/wandb/settings
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Loading settings from /Users/lisa/Documents/atari/wandb/settings
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'environment_test.py', 'program': '/Users/lisa/Documents/atari/environment_test.py'}
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:_log_setup():506] Logging user logs to /Users/lisa/Documents/atari/wandb/run-20240515_203707-rkyd22ol/logs/debug.log
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:_log_setup():507] Logging internal logs to /Users/lisa/Documents/atari/wandb/run-20240515_203707-rkyd22ol/logs/debug-internal.log
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:init():546] calling init triggers
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:init():602] starting backend
2024-05-15 20:37:07,449 INFO    MainThread:71108 [wandb_init.py:init():606] setting up manager
2024-05-15 20:37:07,453 INFO    MainThread:71108 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 20:37:07,456 INFO    MainThread:71108 [wandb_init.py:init():613] backend started and connected
2024-05-15 20:37:07,458 INFO    MainThread:71108 [wandb_init.py:init():701] updated telemetry
2024-05-15 20:37:07,458 INFO    MainThread:71108 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2024-05-15 20:37:07,824 ERROR   MainThread:71108 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-15 20:37:08,836 WARNING MsgRouterThr:71108 [router.py:message_loop():77] message_loop has been closed
